apiVersion: v1
kind: LimitRange
metadata:
  name: memory-resource-constraint
spec:
  limits:
  - default:
      cpu: 1Gi # limit
    defaultRequest:
      cpu: 1Gi # request
    max:
      cpu: 1Gi # limit
    min:
      cpu: 500Mi # request
    type: Container
    