apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
spec:
  hard: # 현재 네임스페이스에 리소스 요청 및 한계를 지정
    requests.cpu: 4
    requests.memory: 4Gi
    limits.cpu: 10
    limits.memory: 10Gi